services:
  db:
    image: mongo
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db


  api:
    build: ./api
    restart: always
    ports:
      - '8000:8000'
    volumes:
      - /app/node_modules
      - ./api:/app
    depends_on:
      - db

  # client:
  #   build: ./client
  #   restart: always
  #   ports:
  #     - '3000:3000'
  #   volumes:
  #     - /app/node_modules
  #     - ./client:/app
  #   depends_on:
  #     - api

volumes:
  mongo_data: